/**
 * This package contains the Dead Files Color Decorator plug-in for Eclipse.
 * The plug-in needs an colors.txt generated by an external tool. A tool for
 * this purpose for PHP can be found at <a href="https://github.com/hostnet">GitHub</a>
 */
package nl.hostnet.deadfiles;